# Generated by Django 5.0.2 on 2024-02-15 04:50

import django.utils.timezone
import formApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('empId', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('status', models.BooleanField()),
                ('address', models.CharField(max_length=255, validators=[formApp.models.comma_separated_validator])),
                ('dateOfBirth', models.DateField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=5)),
                ('duration', models.DurationField()),
                ('email', models.EmailField(max_length=254)),
                ('resume', models.FileField(upload_to='files/')),
                ('result', models.FloatField()),
                ('image', models.ImageField(upload_to='')),
                ('age', models.IntegerField()),
                ('otherData', models.JSONField()),
                ('otherUrl', models.URLField()),
                ('uid', models.UUIDField()),
            ],
        ),
    ]
